#!/bin/bash

set -eu

# config-tool is meant to be sourced where required.

# Set configuration option
# config_set <config_file> <key> <value> 
config_set()
{
    if [ $# -eq 3 ]; then
	file=$1
        key=$2
        value=$3

	if ! [ -f "$file" ]; then
            touch "$file"
        fi

	sed -i "/^$key:/d" "$file"
        echo "$key: $value" >> "$file"
    fi
}

# Get configuration option
# config_get <config_file> <key>
# returns <value>
config_get()
{
    if [ $# -eq 2 ]; then
	file=$1
	key=$2

	if ! [ -f "$file" ]; then
	    touch "$file"
	fi

        value=$(grep -oP "$key: \K\S+" < "$file")
        echo "$value"
    fi
}

# Reset the configuration
# config_reset <config_file>
config_reset()
{
    if [ $# -eq 1 ]; then
        file=$1

	rm -rf "$file"
    fi
}
